# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

maxRequestedChanges:
  NONE: 0
updateBranch: true
deleteBranchAfterMerge: true
requiredLabels:
- merge
blockingLabels:
- blocked
