sudo: false
language: node_js
node_js:
- '8.3'
notifications:
  email: false

env:
  global:
    secure: Z/rjYonsLdCDk+RVfNkQWy3nRXK6g9nzlqvm2ronYyjH/sLoKLLyLcKgeybWgiPC3tOaY6veOx4jW/weEFueyJO0TvfwMbqwtvuOhn/wJut4JJLKtSJCarh7iznuFa7TsAcRMPzRe2Ux1wi2x4nmxduneYbJS/iXPXTmUXWjQrk1hgs4iaZegp48Z+gF5yMAL2NiNvWwkVMGHuDPpcoO//r+FEO62ETwi0NMFue00vg1tJbHwy0O2DRHvq0mFF0aPpwBGw6pYQG7dRiGBeA/oUghzcX9xeWGRbs0AIB0u5iUz2TT+Ss8o8Z7KuIjaqpsEnng6ojRnxp6Sjd43Ro1ifhUaxZq1Nxa3rPIuju+xmHvzT2wmFVmM8sRXTItSeQhKlzQuRM1BgOlvU446G+xxAeKtxjImhd7hodfUat0RMvlSFcA6cSkcFYSIYwthrQAqPHzjNgNek7i0yxu1PO1nW/lQcXH8RevZJBzxB7dYNY9O3k/T8yaRSfgZbCXpO1ih8T4Oz3myAp8cV36LCDOuhD197EK3xOgj2tL0tl984J3flHCr3cHv1rZZOiqa1lkVQG6QBktC7Nm4jmMTIUBRPd5VKpdUBQZA/wGuLqHDMdjjSUkPCEz41RUcxbc8tX1shm+yF75/NcSFJpIA7f+v03eAxMPx/ex6vi9eKPltoo=

jobs:
  include:
  - stage: build
    script: npm run build
  - stage: test
    script: npm run test:travis
  - stage: release
    node_js: lts/*
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release
